name: Create address update issue
on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  create_issue:
    name: Create address update issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set last month as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "LAST_MONTH=$(date -d "$(date '+%Y%m01') 1 month ago" "+%Y年%m月")" >> $GITHUB_ENV

      - name: Create address update issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "champierre"
          labels: "住所データ変更"
          title: "国土地理協会 ${{ env.LAST_MONTH }}更新 地名変更情報の住所を追加"
          body: |
            # リクエストの種類(必須)

            - [x] 追加
            - [ ] 修正
            - [ ] 削除

            # 対象となる住所(必須)

            ```
            ```

            # 参考情報・URL(オプション)

            - https://kokudo.or.jp/place/

            # 備考(オプション)

            特になし
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
