name: Deploy Staging API
on:
  push:
    branches:
      - develop
    tags:
      - "!*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir data || true
      - run: npm install
      - name: Build Nagano, Hokkaido, and Nara data
        run: node bin/build.js 20,1,29
      - name: Test
        run: npx mocha
  deploy-staging-api:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir data || true
      - run: npm install
      - run: NODE_OPTIONS="--max-old-space-size=4096" node bin/build.js
      - name: sqlite3 install
        run: sudo apt install libsqlite3-dev
      - name: Generate csv file from sqlite3
        run: sqlite3 -header -csv data/latest.db "select * from addresses;" > data/latest.csv
      - run: node bin/build-api.js
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        working-directory: api
        run: aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }}/develop --delete --cache-control "public, max-age=604800, immutable"
